name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Debug current location
        run: |
          pwd
          ls -la
          
      - name: Navigate to React directory
        run: |
          cd $GITHUB_WORKSPACE/react_frontend || cd react_frontend || echo "Already in correct directory"
          pwd
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: react_frontend

      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE/react_frontend || cd react_frontend
          npm run build
          
      - name: Verify build output
        run: |
          cd $GITHUB_WORKSPACE/react_frontend || cd react_frontend
          ls -la dist || echo "No dist directory found!"

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: react_frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo for deployment
        uses: actions/checkout@v3
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./deploy-dist

      - name: Verify download
        run: |
          ls -la ./deploy-dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy-dist
          force_orphan: true